[package]
name = "fesh_comp"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[dependencies]
iced-x86 = "1.21.0"
xz2 = "0.1.7"
object = "0.32.0"
rayon = "1.8.0"
byteorder = "1.5.0"
